language: node_js
node_js:
- '8'
env:
  - NODE_ENV=production
script:
  - npm install
deploy:
  provider: npm
  skip_cleanup: true
  email:
    secure: lZ+YXcuRL8g1oHRgOy19EL15YSJRPOasKd9b0vizqxFCXsFtfa3SdVCUaqiKLXNTrpR7DnDnTBpbTkgWxoFHyNGacFXftOEgO3W5CBtHpiEnMW37froOLbtiqHtGso6mptknhXSWSBuCBWnaoUndCxPzXPQS6SKemNwjQqzOEiNCfOFw7CKSQV89dmIrYl9STHY9/ELqX0u/+lTjJyk38fhvcO5qYJTmcvUzmKtYsaloTYHt/ZLg8Mkfs12I4vQ/lL8jMyc9PwRIho754W4g7mWQn0LLuZ/Wp0Rl+JTaCW6uVZRaJwOa1Y4rZKmK4+w7uRg6ywHXRRaBqkmx9T7MsI2wVutQXTRZ7ah5w9hkqPTJzNmALobCM8muh0rYEWjDq42FakFjd+bEe3Qi3dw9DnZ0oN1yzPu3JWC9s40IzqvttR/be4vZJK+vV68gfWoXMGk7s+nnhzp96VxeXdaaNRMh0Mk9m6erA6QoB4JpbwhvBsd7F8Va4jWC8fX4HrTpFTF/fp6/6VVcqTA8r+870t1gAsfcb4yYnbNHpAGz905fvzXx+xhMdYdK6s4zQZOVtyKTivP82rvhByl0J7t6Ep4D9svWBDdDRaOhwHeySUN7/t4PeK7pwDulaCOEh7o35BJMMq5uMmx051bT+VF7cFQk/mNFHTA4UjE8yii2lVI=
  api_key:
    secure: ALTrwhAusYzlY3oGggr+aADscbNnet8irQfElBdg3zoiUZWidO0YOMY/O/HCBZff9S8xLxSzLJ7UWCr+TCYLgD8KaQAZf8xxCRGdQFYiWWs0evLi2JqvvXCh+U8HBAD3GkCFrZPHKdsfAI6x5oE9kajF3Tv4qmB95xl6uFwt1CAOo1u5KdqjsSZhG3Mf8v7CXBfyEpmni+RtIozP2Rc1nd43lyqlWxkYCnLopMGsLAejs2DERvEhi/vnYQamg4o8W+5+xzmAr8kmf5wJ+pHqMbIur4Ei5lBPpsbPwkatScWldr/ipRzNegBlqgKaY0DVzoiaF3lZ2E9jMWUmsMBZzQlFzb5s9fUl6myTXJXPu5khm4rXtR91nPVvZv9hjt+MLQMABpVh6gPjGbI2R5DakRKRCcRGSMutIepWJoGuuImMOL1ZBlDzf+G2h6ft6Doc79X4n8+cYBPUCGRmrMdZuqboRKeLCL9kJnDArxRwDI2ksSjnJdATD2LItR6YntbXlnNrKTgNVCUcqbFSrQmeq9CgrrBJXs+EA6jpqeZxJLlPxWm4NoV7o88HXSemg1h42sicHYgsdvhLXH3mfwL+75wGT2N5odAoZsfoEbo9i6dBJf0+b+0aB4lwxwx8o6kRYGoeApW8npjvnCS4IDVcPZUnWbXGwSNREVtgBR3Htko=
  on:
    branch: master