language: node_js
node_js:
- '8'
env:
- NODE_ENV=production
script:
- npm install
deploy:
  provider: npm
  skip_cleanup: true
  email:
    secure: lZ+YXcuRL8g1oHRgOy19EL15YSJRPOasKd9b0vizqxFCXsFtfa3SdVCUaqiKLXNTrpR7DnDnTBpbTkgWxoFHyNGacFXftOEgO3W5CBtHpiEnMW37froOLbtiqHtGso6mptknhXSWSBuCBWnaoUndCxPzXPQS6SKemNwjQqzOEiNCfOFw7CKSQV89dmIrYl9STHY9/ELqX0u/+lTjJyk38fhvcO5qYJTmcvUzmKtYsaloTYHt/ZLg8Mkfs12I4vQ/lL8jMyc9PwRIho754W4g7mWQn0LLuZ/Wp0Rl+JTaCW6uVZRaJwOa1Y4rZKmK4+w7uRg6ywHXRRaBqkmx9T7MsI2wVutQXTRZ7ah5w9hkqPTJzNmALobCM8muh0rYEWjDq42FakFjd+bEe3Qi3dw9DnZ0oN1yzPu3JWC9s40IzqvttR/be4vZJK+vV68gfWoXMGk7s+nnhzp96VxeXdaaNRMh0Mk9m6erA6QoB4JpbwhvBsd7F8Va4jWC8fX4HrTpFTF/fp6/6VVcqTA8r+870t1gAsfcb4yYnbNHpAGz905fvzXx+xhMdYdK6s4zQZOVtyKTivP82rvhByl0J7t6Ep4D9svWBDdDRaOhwHeySUN7/t4PeK7pwDulaCOEh7o35BJMMq5uMmx051bT+VF7cFQk/mNFHTA4UjE8yii2lVI=
  api_key:
    secure: zXQhIkTSPTQ2k4u7TGG+WvPJXZxLmcWsudIvVK6JFPq00fW2YTwR/VS9R543jWgG8QuJQ6GnLC5jlje90yXSzCxoYq5xvcMU/Yzqx5x5oj0OHMZoVkI59kjdt8jtCcuYrz99Aew14FSEBbsxvy2vbp7er30cMvowq+5husGVWSrJNS4xvLHGw7FD6PFgfzuuOMrJc02qi5zeQJ7hKbJLjuN4JH0RSb2mgWWlTM8e5p2e2ZEU9ERfR5UQ14dd1Y/I4kors5zqNrmUfAC0eFYoV5PYv+wnCsH4qM2Mrbiw10xY4E1izZXCeo8bpvVhuiSzqxxl5yzlc9Yhp/0kjE6wvqQKKrCkX5Bl0dWnDY4B8GA4KQBDxd1qhnEze6e6i/3Cv6BTvFEYWUU9j3owPQIKaS/dg8E1RKJk2ogeBjhNwQP/ffQmJAsJXOwLpotlGuw6SdBxPvCAK/Vbp8SyHOQHhpsF8fwElKjO9IXTVTvt1SQ+2jC5ACPImf02sQgDNCIScnLZXIZinLKNG5e0vsHOPrm7Koat878H939IGMcYUcxIIx9X6Ss0GoTkody/3Glo4dHlFYfzMy60QKgJhPKgHGCVTC+oynP98rvvrvhJiKu7DDR0oXbNV5CkVmeNHp6/Xj0ElPTtd1NWz4lXygt6EZhMfjevY0Wn2mtY6L0rcEM=
  on:
    branch: master
